### ISSUE TITLE
Feature Request -- Ability to edit page properties from page editor screen

### ISSUE THREAD

**Issue by joshrcook** [wvuweb/cleanslate-cms#116] opened 2015-01-28 17:23 UTC
In order to edit page properties, you have to exit the page editor screen and find it again in the list of pages.  It would be nice, especially when doing things like editing page Javascript.

**Comment by adamjohnson** [comment] 2015-01-28 18:12
This is a duplicate of #38. Please +1 that issue.

**Closed as completed by adamjohnson** 2015-01-28 18:12 UTC
