### ISSUE TITLE
Mercury Formatting Issue for text without HTML Tags

### ISSUE THREAD

**Issue by TatsuJohnson** [wvuweb/cleanslate-cms#223] opened 2016-12-06 16:57 UTC
Issue:
Text that have been published in CleanSlate without proper HTML tags output a string that is wrapped in a div. This makes it hard/impossible to style for. Ideally, publishers will always use HTML tags, but it doesn't always happen. 

Example:
http://www.law.wvu.edu/news/2016/07/01/wvu-law-lcld

Suggested solution: 
Maybe make it so that text is automatically put in "p" tag instead of a div. Ideally, I would like to see a way to warn publishers that their text isn't using proper HTML tags. Maybe by highlighting it in the editor.

**Comment by jasonmarkle** [comment] 2016-12-08 13:55
@TatsuJohnson can you provide you specs and how to replicate?

**Comment by adamjohnson** [comment] 2019-05-14 21:43
This is a duplicate of #2. 

FYI, to enforce starting with a `<p>` tag, you could do something like this:

```html
<r:editable_region name="main">
  <p>I start as a paragraph</p>
</r:editable_region>
```

**Closed as completed by adamjohnson** 2019-05-14 21:43 UTC
Labels: duplicate, mercury editor
