### ISSUE TITLE
Code window UI cuts off at bottom of screen after heavy usage

### ISSUE THREAD

**Issue by jasonmarkle** [wvuweb/cleanslate-cms#174] opened 2015-07-31 12:49 UTC
## Steps to reproduce the issue (Update: I think this is being caused if you resize the browser window)
1. Log in to CleanSlate.
2. Click pages > open page in new tab > code.
3. Close code > resize browser window > open code again.
## Results

It cuts off at the bottom of the browser window. So this in turn makes it impossible to save changes. You would think I'd notice it from the get go, but sometimes I'm so engrossed with what I'm working on I miss it, have to pull the code to sublime, refresh the browser, then re-open and re-insert the changes.
## Expected results

It's supposed to just (from what I assume) stay at the browsers height.
### Environment

   Chrome Version 43.0.2357.132 (64-bit)
   OSX Yosimitee 10.10.4 (14E46)

![screen shot 2015-07-31 at 8 38 46 am](https://cloud.githubusercontent.com/assets/5209650/9007624/12e9b93e-3761-11e5-821b-995b999089bb.png)

![screen shot 2015-08-04 at 9 57 42 am](https://cloud.githubusercontent.com/assets/5209650/9062314/ab89d03a-3a8f-11e5-9d46-1b968040e57f.png)

**Comment by adamjohnson** [comment] 2015-08-10 21:25
I'm unable to reproduce this issue following the instructions provided. 

If you run into this in the future, keep in mind you can hit ⌘/CTRL + S to save and close the modal.

Closing this if/until we see it again.

**Closed as completed by adamjohnson** 2015-08-10 21:25 UTC
