### ISSUE TITLE
link issue

### ISSUE THREAD

**Issue by ldbridges** [wvuweb/cleanslate-cms#161] opened 2015-05-14 15:06 UTC
## Steps to reproduce the issue
1. Log in to CleanSlate.
2. Create a link
3. copy and paste the link
## The link is incorrect missjng data-page-id

![screen-shot-2015-05-14-at-2 46 10-pm](https://cloud.githubusercontent.com/assets/12446920/7639268/9aea3620-fa48-11e4-9be0-22991ca80ee5.jpg)

it copies the editor link but doesn't include the data attributes

**Comment by dmolsen** [comment] 2015-05-14 15:12
@ldbridges -

We need a bit more information before we can address this issue. Could you please reply to this issue with the info that we ask for under "[bug reports](https://github.com/wvuweb/cleanslate-cms/blob/master/CONTRIBUTING.md)"? The steps to reproduce and the screenshot are really what we need.

Once we get that we can do a better job of trying to recreate your problem and troubleshoot it. Thanks.

**Comment by adamjohnson** [comment] 2015-05-14 15:21
Lisa, can you give us an example of the markup of link you're copying? Also, can you show us the resulting markup after you paste it into CleanSlate? This will let us better troubleshoot this issue.

Looks like @dmolsen replied as you were editing your issue.

**Comment by ldbridges** [comment] 2015-05-14 18:51
I added a screen shot, sorry I am doing this for the first time.

**Comment by dmolsen** [comment] 2015-05-14 19:15
@ldbridges -

No worries :) By default Clean Slate sanitizes mark-up that gets pasted into the editor. Hence the missing attributes. Before we look at creating a workaround what is the end goal of using `data-page-id` on the link? 

FWIW, the screenshot you shared must have been shrunk by GitHub because I can't read it. Feel free to just copy & paste code into your comment. Thanks.

**Comment by nreckart** [comment] 2015-05-14 20:07
@dmolsen 

The data-page-id is a system attribute used to build internal page links. There's a similar attribute used for asset/file links.

**Comment by dmolsen** [comment] 2015-05-18 13:47
@ldbridges -

While @nreckart explained what it's for could you let me know what problem you were looking to solve by copying and pasting? I'm just trying to get a handle on if we need to develop a workaround and, if so, what kind we need. Thanks.

PS - if it's easier for me to jump over there just let me know

**Comment by dmolsen** [comment] 2015-05-26 17:58
@ldbridges -

I'm assuming you found a workaround yourself. If you want to discuss this let me know. Otherwise I will close this issue tomorrow, Wednesday 27 at COB.

**Comment by nreckart** [comment] 2015-07-29 19:29
So this has reared it ugly head again and I have a better understanding of a scenario in which this can break links. 

It is not uncommon for a content editor to reorganize the links on a page. They select an existing file/page link, which has a special data id attribute, cut it, and paste it elsewhere on the same page. When the link is pasted, the special data id attribute gets stripped due to the sanitizing.

**Closed as completed** 2015-11-12 18:25 UTC
Labels: Q3 delivery
