### ISSUE TITLE
Feature Request: Blog Archive List

### ISSUE THREAD

**Issue by architarious** [wvuweb/cleanslate-cms#185] opened 2015-11-06 19:11 UTC
# Proposal

If a user comes onto one of our blogs and is looking for a story from about a few months or sometimes years back, they have to browse through dozens or potentially hundreds of different posts looking for their story. It would be ideal if there was a dynamically generated list on the side that could provide a link to (possibly cached) list of all articles that where posted in a specific month or year.

Here's an example of how we used to use this type of functionality in old slate:

Source: http://cpass.wvu.edu/news 
![screenshot of current CPASS blog](http://i.imgur.com/2xyQsrm.png)
![scroonshot of CPASS blog archives](http://i.imgur.com/y8Jo4n1.png)

_EDIT:_
## Thoughts on implementation

Check out #186 , except you would be focusing on r:article:published_at instead of r:article:tags

**Comment by adamjohnson** [comment] 2015-11-09 16:36
I've had 3-4 other people contact me regarding this request. :+1: 

Here's the date list:

![blog-archives-list](https://cloud.githubusercontent.com/assets/575865/11039481/e477b744-86d5-11e5-8d0d-3ec9f1f79c84.png)

And, after you click on "June 2015", it takes you here:

![blog-archives-list-results](https://cloud.githubusercontent.com/assets/575865/11039480/e46d0d12-86d5-11e5-9dac-d7d71e919ad0.png)

**Comment by nreckart** [comment] 2015-12-02 21:43
The archive functionality is already there, the issue is building the links. 

foo.com/blog/2015/01/21
foo.com/blog/2015/01/22
foo.com/blog/2015/01
foo.com/blog/2015/02
foo.com/blog/2015/03
foo.com/blog/2015
foo.com/blog/2014

Right now you have to manually create the links, which can be done in the template using looping logic or via javascript. Not ideal, but you can still provide access to the archives in the short term. 

Implementing tags in CleanSlate to automatically build the links is still a valid issue.

**Comment by adamjohnson** [comment] 2015-12-07 15:36
@nreckart Can you give a code example of how this looping logic will work? If so, I can add it to the default templates in the CleanSlate Toolkit and Brand Patterns.

**Comment by nreckart** [comment] 2015-12-07 21:38
``` html
<h4>Archive</h4>
<r:set_var name="archive_months" value="Dec2015, Nov2015, Oct2015, Sept2015" />
<r:loop:each items="{$archive_months}">
  <a href="<r:page:url />/<r:date_format value="{item}" format="%Y" />/<r:date_format value="{item}" format="%m" />">
    <r:date_format value="{item}" format="%B" /> <r:date_format value="{item}" format="%Y" />
  </a>
  <br/>
</r:loop:each>
```

It isn't pretty, but it gets the job done. This uses the 'archive_months' variable to store a comma separated list of Month/Year items. In this example I set the variable in the template, but it could easily come from a custom page attribute, which could then be maintained via the UI.

I don't know that I would recommend adding it to the toolkit or patterns since it really isn't the best solution in the world. It's basically a stopgap.

**Comment by nreckart** [comment] 2015-12-08 21:09
What do we want the HTML output for this to be? I envision it working like the menu tags.

**Comment by adamjohnson** [comment] 2015-12-08 21:26
I'd be happy with outputting these as a `<ul>`. That said, there's probably some useful options to display.
- `show-article-count` - Boolean, displays the number of articles for the given link (like [this](http://whitewaterfreestyle.com/archives/))
- `date-format` - How to display the date, eg 1/1/16 or January 1, 2016.
- ...others...?

What template will "Archives for June 2015" use (head nod to the CPASS example above)? `blog_index.html`?

CSS Tricks has their archive listed in `<article>` tags:

https://css-tricks.com/archives/

Maybe not particularly relevant but I thought it was interesting to see different ways people might implement this.

**Comment by zeroedin** [comment] 2015-12-08 21:28
Example of what WVUToday's use case might be: http://wvutoday.wvu.edu/home/story_archive

**Comment by adamjohnson** [comment] 2015-12-08 21:28
Moar examples:

http://wvutoday.wvu.edu/n/2015/12

**Comment by jasonmarkle** [comment] 2015-12-10 16:16
+1

Currently working on the blog index for the new engineering site and we have the ability to sort by category (labels) and dates in the old system. Ex: [Statler News](http://www.statler.wvu.edu/news/news.php)

**Comment by jasonmarkle** [comment] 2015-12-10 16:32
@nreckart Could you use that looping logic with labels also? Or is it specific to the date formats since they are an existing radius tag?

@adamjohnson +1 on the default being the blog index. Breaking it up in to another view would be confusing since you're just reorganize the content in a more specific way.

**Comment by nreckart** [comment] 2015-12-10 18:03
@jasonmarkle You can use generic looping for anything. You would want to loop over a specified list of tags to build the 'category' links. You'd need to specify the tags because, otherwise, you'd get every tag used anywhere on the site.

``` html
<r:loop:each items="tag1, tag2, tag3">
   <!-- build links here -->
</r:loop:each>
```

**Comment by jasonmarkle** [comment] 2015-12-10 18:08
@nreckart so essentially create a variable:

``` html
<r:set_var name="archive_tags" value="Tag1, Tag2, Tag3" />
   <r:loop:each items="{$archive_tags}">
```

Is this correct?

**Comment by nreckart** [comment] 2015-12-10 18:27
You don't necessarily have to set a variable. The value can be embedded directly in the tag as in the example. If you want the tag list to be manageable via the admin UI, you could use a custom page/template attribute.

**Comment by nreckart** [comment] 2015-12-10 18:58
Here's what we'll start with. This is ready to go now, but hasn't been deployed. @adamjohnson, now is the time to change the default classes applied to the elements.

**New tag:** `<r:blog:archive:monthly />`

**Attributes:**
- _date_format_: How to output the date portion of the data. Uses the same syntax as `<r:date_format>` (Default: %B %Y)
- _include_count_: (true|false) Whether or not to include a `<span>` with the number of articles for each item (Default: true)
- _ul_class_: The class applied to the `<ul>` (Default: cs-blogArchive-monthly).
- _count_class_: The class applied to the `<span>` containing the article count (Default: cs-blogArchive-count)

**Examples:**

``` html
<r:blog:archive:monthly />

<!-- Output -->
<ul class="cs-blogArchive-monthly">
  <li><a href="http://somedomain.com/news/2014/09">September 2014 <span class="cs-blogArchive-count">1</span></a></li>
  <li><a href="http://somedomain.com/news/2013/11">November 2013 <span class="cs-blogArchive-count">2</span></a></li>
  <li><a href="http://somedomain.com/news/2012/09">September 2012 <span class="cs-blogArchive-count">1</span></a></li>
  <li><a href="http://somedomain.com/news/2012/03">March 2012 <span class="cs-blogArchive-count">1</span></a></li>
  <li><a href="http://somedomain.com/news/2011/05">May 2011 <span class="cs-blogArchive-count">1</span></a></li>
  <li><a href="http://somedomain.com/news/2011/04">April 2011 <span class="cs-blogArchive-count">2</span></a></li>
</ul>
```

``` html
<r:blog:archive:monthly date_format="%b %Y" include_count="true" ul_class="awesome-archives" count_class="article-count"/>

<!-- Output -->
<ul class="awesome-archives">
  <li><a href="http://somedomain.com/blog/2014/09">Sep 2014 <span class="article-count">1</span></a></li>
  <li><a href="http://somedomain.com/blog/2013/11">Nov 2013 <span class="article-count">2</span></a></li>
  <li><a href="http://somedomain.com/blog/2012/09">Sep 2012 <span class="article-count">1</span></a></li>
  <li><a href="http://somedomain.com/blog/2012/03">Mar 2012 <span class="article-count">1</span></a></li>
  <li><a href="http://somedomain.com/blog/2011/05">May 2011 <span class="article-count">1</span></a></li>
  <li><a href="http://somedomain.com/blog/2011/04">Apr 2011 <span class="article-count">2</span></a></li>
</ul>
```

**Comment by zeroedin** [comment] 2015-12-10 19:00
:+1:

**Comment by adamjohnson** [comment] 2015-12-10 19:59
Here's my suggestion on default class names:

``` html
<r:blog:archive:monthly />

<!-- Output -->
<ul class="cs-blog-archive cs-blog-archive--monthly">
  <li><a href="http://somedomain.com/news/2014/09">September 2014 <span class="cs-blog-archive__count">1</span></a></li>
  <li><a href="http://somedomain.com/news/2013/11">November 2013 <span class="cs-blog-archive__count">2</span></a></li>
  <li><a href="http://somedomain.com/news/2012/09">September 2012 <span class="cs-blog-archive__count">1</span></a></li>
  <li><a href="http://somedomain.com/news/2012/03">March 2012 <span class="cs-blog-archive__count">1</span></a></li>
  <li><a href="http://somedomain.com/news/2011/05">May 2011 <span class="cs-blog-archive__count">1</span></a></li>
  <li><a href="http://somedomain.com/news/2011/04">April 2011 <span class="cs-blog-archive__count">2</span></a></li>
</ul>
```

Being able to customize them via the Radius tag is awesome. :+1: 

When this has been implemented, I'll add them to Brand Patterns, the CleanSlate toolkit, and document them in the tag index on the CleanSlate help site.

**Comment by nreckart** [comment] 2015-12-11 15:48
This has been deployed with the CSS class changes.

**Comment by adamjohnson** [comment] 2015-12-14 21:40
Docs have been written: http://cleanslatecms.wvu.edu/how-to/theme-development/tag-index/r-blog-attr

**Comment by adamjohnson** [comment] 2015-12-15 21:30
This tag has been added to the Brand Patterns repo: 

https://github.com/wvuweb/brand-patterns/commit/756e3a3628ebb88a2a5cb1027ca35eeee0fdb64b

Only thing left is to get it to render in hammer, but there's [already an issue](https://github.com/wvuweb/hammer/issues/39) for that. Closing this issue. Nice work everyone!

**Closed as completed by adamjohnson** 2015-12-15 21:30 UTC
Labels: feature request
